//! R.java / proguard / text-symbol generation.
//!
//! Port of `java/JavaClassGenerator.{h,cpp}`, `java/ProguardRules.cpp`
//! (collection subset), and the R.txt writer.

use super::LinkContext;
use crate::diag::Diagnostics;
use crate::res::table::ResourceTable;
use crate::res::value::{Styleable, ValueKind};
use crate::res::{ResourceType, Source};
use crate::xml::Element;
use anyhow::Result;
use std::fmt::Write as _;

#[derive(Debug, Clone, Default)]
pub struct JavaGenOptions {
    pub custom_package: Option<String>,
    pub extra_packages: Vec<String>,
    pub javadoc_annotations: Vec<String>,
    pub private_symbols: Option<String>,
    /// `--non-final-ids` (implied by `--static-lib`).
    pub non_final_ids: bool,
    pub rename_manifest_package: Option<String>,
}

const HEADER: &str = "/* AUTO-GENERATED FILE. DO NOT MODIFY.\n *\n * This class was automatically generated by the\n * aapt tool from the resource data it found. It\n * should not be modified by hand.\n */\n\n";

/// Transforms a resource entry name into a Java field name (`.` and
/// `-` become `_`). Mirrors `JavaClassGenerator::TransformToFieldName`.
pub fn to_field_name(name: &str) -> String {
    name.replace(['.', '-'], "_")
}

/// Generates the R classes: the main one plus copies for
/// `--extra-packages`. Returns (java package, source) pairs.
pub fn generate_java_classes(
    table: &ResourceTable,
    _manifest: &Element,
    context: &LinkContext,
    options: &JavaGenOptions,
    _diag: &Diagnostics,
) -> Result<Vec<(String, String)>> {
    let main_package = options
        .custom_package
        .clone()
        .unwrap_or_else(|| context.compilation_package.clone());

    let source = generate_r_java(table, &main_package, options);
    let mut out = vec![(main_package, source.clone())];
    for extra in &options.extra_packages {
        for package in extra.split(':').filter(|p| !p.is_empty()) {
            let copy = regenerate_package_line(&source, package);
            out.push((package.to_string(), copy));
        }
    }
    Ok(out)
}

fn regenerate_package_line(source: &str, package: &str) -> String {
    let mut out = String::with_capacity(source.len());
    for line in source.lines() {
        if let Some(rest) = line.strip_prefix("package ") {
            let _ = rest;
            out.push_str(&format!("package {package};"));
        } else {
            out.push_str(line);
        }
        out.push('\n');
    }
    out
}

/// Generates one R.java for `java_package`.
pub fn generate_r_java(
    table: &ResourceTable,
    java_package: &str,
    options: &JavaGenOptions,
) -> String {
    let finality = if options.non_final_ids { "" } else { "final " };
    let mut out = String::new();
    out.push_str(HEADER);
    let _ = writeln!(out, "package {java_package};");
    out.push('\n');
    for annotation in &options.javadoc_annotations {
        let _ = writeln!(out, "/** {annotation} */");
    }
    out.push_str("public final class R {\n");

    for (_, types) in table.sorted_view() {
        // Group named types by their Java class name (custom-named
        // types like `string.v2` collapse into `string`).
        let mut current_class: Option<String> = None;
        for (ty, entries) in types {
            let class_name = ty.named_type.ty.as_str().replace('^', "");
            if current_class.as_deref() != Some(&class_name) {
                if current_class.is_some() {
                    out.push_str("  }\n");
                }
                let _ = writeln!(out, "  public static final class {class_name} {{");
                current_class = Some(class_name.clone());
            }

            if ty.named_type.ty == ResourceType::Styleable {
                for entry in entries {
                    if let Some(ValueKind::Styleable(styleable)) = entry
                        .values
                        .first()
                        .and_then(|v| v.value.as_ref())
                        .map(|v| &v.kind)
                    {
                        write_styleable(&mut out, &entry.name, styleable, finality);
                    }
                }
            } else {
                for entry in entries {
                    let Some(id) = entry.id else { continue };
                    let _ = writeln!(
                        out,
                        "    public static {finality}int {}=0x{:08x};",
                        to_field_name(&entry.name),
                        id.0
                    );
                }
            }
        }
        if current_class.is_some() {
            out.push_str("  }\n");
        }
    }
    out.push_str("}");
    out.push('\n');
    out
}

fn write_styleable(out: &mut String, name: &str, styleable: &Styleable, finality: &str) {
    // Sort attribute references by resource ID, mirroring the
    // JavaClassGenerator's sorted styleable layout.
    let mut sorted: Vec<_> = styleable.entries.iter().collect();
    sorted.sort_by_key(|reference| reference.id.map(|id| id.0).unwrap_or(0));

    let field_name = to_field_name(name);
    let ids: Vec<String> = sorted
        .iter()
        .map(|r| format!("0x{:08x}", r.id.map(|id| id.0).unwrap_or(0)))
        .collect();
    let _ = writeln!(
        out,
        "    public static {finality}int[] {field_name}={{\n      {}\n    }};",
        ids.join(", ")
    );
    for (index, reference) in sorted.iter().enumerate() {
        let Some(attr_name) = &reference.name else {
            continue;
        };
        let mut suffix = String::new();
        if !attr_name.package.is_empty() {
            suffix.push_str(&attr_name.package.replace('.', "_"));
            suffix.push('_');
        }
        suffix.push_str(&to_field_name(&attr_name.entry));
        let _ = writeln!(
            out,
            "    public static {finality}int {field_name}_{suffix}={index};"
        );
    }
}

/// Generates the R.txt symbol list (`--output-text-symbols`).
pub fn generate_text_symbols(table: &ResourceTable) -> String {
    let mut out = String::new();
    for (_, types) in table.sorted_view() {
        for (ty, entries) in types {
            for entry in entries {
                if ty.named_type.ty == ResourceType::Styleable {
                    let _ = writeln!(out, "int[] styleable {} {{ }}", to_field_name(&entry.name));
                    if let Some(ValueKind::Styleable(styleable)) = entry
                        .values
                        .first()
                        .and_then(|v| v.value.as_ref())
                        .map(|v| &v.kind)
                    {
                        let mut sorted: Vec<_> = styleable.entries.iter().collect();
                        sorted.sort_by_key(|r| r.id.map(|id| id.0).unwrap_or(0));
                        for (index, reference) in sorted.iter().enumerate() {
                            if let Some(name) = &reference.name {
                                let mut suffix = String::new();
                                if !name.package.is_empty() {
                                    suffix.push_str(&name.package.replace('.', "_"));
                                    suffix.push('_');
                                }
                                suffix.push_str(&to_field_name(&name.entry));
                                let _ = writeln!(
                                    out,
                                    "int styleable {}_{suffix} {index}",
                                    to_field_name(&entry.name)
                                );
                            }
                        }
                    }
                } else if let Some(id) = entry.id {
                    let _ = writeln!(
                        out,
                        "int {} {} 0x{:08x}",
                        ty.named_type.ty.as_str().replace('^', ""),
                        to_field_name(&entry.name),
                        id.0
                    );
                }
            }
        }
    }
    out
}

// ───────────────────────── proguard ─────────────────────────

/// A class to keep, with the source it was referenced from.
#[derive(Debug, Default)]
pub struct KeepSet {
    pub conditional: bool,
    /// (usage tag, class name, source).
    classes: Vec<(String, String, Source)>,
    /// (class, method signature, source).
    methods: Vec<(String, String, Source)>,
}

impl KeepSet {
    pub fn new(conditional: bool) -> Self {
        KeepSet {
            conditional,
            ..Default::default()
        }
    }

    pub fn add_class(&mut self, usage: &str, class: &str, source: Source) {
        self.classes
            .push((usage.to_string(), class.to_string(), source));
    }

    pub fn add_method(&mut self, class: &str, signature: &str, source: Source) {
        self.methods
            .push((class.to_string(), signature.to_string(), source));
    }

    /// Collects keep rules from a linked XML document (layouts:
    /// custom views; manifest: components). Mirrors the collectors in
    /// `java/ProguardRules.cpp`.
    pub fn collect_from_xml(&mut self, element: &Element, source_path: &str, kind: XmlKind) {
        let source = Source::with_line(source_path, element.line_number);
        match kind {
            XmlKind::Manifest => {
                if matches!(
                    element.name.as_str(),
                    "activity"
                        | "service"
                        | "receiver"
                        | "provider"
                        | "application"
                        | "instrumentation"
                        | "activity-alias"
                ) {
                    if let Some(name) = element.attr_value(crate::xml::SCHEMA_ANDROID, "name") {
                        self.add_class("AndroidManifest.xml", name, source.clone());
                    }
                    if let Some(backup_agent) =
                        element.attr_value(crate::xml::SCHEMA_ANDROID, "backupAgent")
                    {
                        self.add_class("AndroidManifest.xml", backup_agent, source.clone());
                    }
                    if let Some(app_component) =
                        element.attr_value(crate::xml::SCHEMA_ANDROID, "appComponentFactory")
                    {
                        self.add_class("AndroidManifest.xml", app_component, source.clone());
                    }
                    if let Some(zygote) =
                        element.attr_value(crate::xml::SCHEMA_ANDROID, "zygotePreloadName")
                    {
                        self.add_class("AndroidManifest.xml", zygote, source.clone());
                    }
                }
            }
            XmlKind::Layout => {
                // Custom views: element names containing '.'.
                if element.name.contains('.') {
                    self.add_class("layout", &element.name, source.clone());
                }
                if element.name == "view" || element.name == "fragment" {
                    if let Some(class) = element
                        .attr_value("", "class")
                        .or_else(|| element.attr_value(crate::xml::SCHEMA_ANDROID, "name"))
                    {
                        self.add_class("layout", class, source.clone());
                    }
                }
                if let Some(handler) = element.attr_value(crate::xml::SCHEMA_ANDROID, "onClick") {
                    self.add_method(
                        "android.content.Context",
                        &format!("void {handler}(android.view.View)"),
                        source.clone(),
                    );
                }
            }
            XmlKind::Other => {
                if element.name.contains('.') {
                    self.add_class("xml", &element.name, source.clone());
                }
            }
        }
        for child in element.child_elements() {
            self.collect_from_xml(child, source_path, kind);
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum XmlKind {
    Manifest,
    Layout,
    Other,
}

/// Renders the keep rules. Mirrors `proguard::WriteKeepSet`.
pub fn generate_proguard_rules(keep_set: &KeepSet, no_location_reference: bool) -> String {
    let mut out = String::new();
    let mut seen = std::collections::BTreeSet::new();
    for (usage, class, source) in &keep_set.classes {
        if !seen.insert(class.clone()) {
            continue;
        }
        if !no_location_reference {
            let _ = writeln!(out, "# Referenced at {source}");
            let _ = writeln!(out, "# {usage}");
        }
        let _ = writeln!(out, "-keep class {class} {{ <init>(...); }}");
    }
    let mut seen_methods = std::collections::BTreeSet::new();
    for (class, signature, source) in &keep_set.methods {
        if !seen_methods.insert((class.clone(), signature.clone())) {
            continue;
        }
        if !no_location_reference {
            let _ = writeln!(out, "# Referenced at {source}");
        }
        let _ = writeln!(out, "-keepclassmembers class * {{ *** {signature}; }}");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::res::config::ConfigDescription;
    use crate::res::value::{Item, Value};
    use crate::res::{ResourceId, ResourceName};

    #[test]
    fn r_java_basic() {
        let mut table = ResourceTable::new();
        table
            .add_value(
                ResourceName::new("com.app", ResourceType::String, "app.name"),
                ConfigDescription::default(),
                Value::item(Item::String {
                    value: "x".to_string(),
                    untranslatable_sections: vec![],
                }),
            )
            .unwrap();
        table
            .find_resource_mut(&ResourceName::new(
                "com.app",
                ResourceType::String,
                "app.name",
            ))
            .unwrap()
            .id = Some(ResourceId(0x7f020000));

        let source = generate_r_java(&table, "com.app", &JavaGenOptions::default());
        assert!(source.contains("package com.app;"), "{source}");
        assert!(
            source.contains("public static final class string"),
            "{source}"
        );
        assert!(
            source.contains("public static final int app_name=0x7f020000;"),
            "{source}"
        );
    }

    #[test]
    fn non_final_ids() {
        let mut table = ResourceTable::new();
        table
            .add_value(
                ResourceName::new("com.app", ResourceType::Id, "x"),
                ConfigDescription::default(),
                Value::item(Item::Id),
            )
            .unwrap();
        table
            .find_resource_mut(&ResourceName::new("com.app", ResourceType::Id, "x"))
            .unwrap()
            .id = Some(ResourceId(0x7f010000));
        let options = JavaGenOptions {
            non_final_ids: true,
            ..Default::default()
        };
        let source = generate_r_java(&table, "com.app", &options);
        assert!(
            source.contains("public static int x=0x7f010000;"),
            "{source}"
        );
    }
}
