//! Maps a [`SyntaxKind`] to the exact string the Kotlin script
//! `scripts/kotlin-psi.main.kts` emits for that kind.
//!
//! kotlinc's `IElementType.toString()` produces lowercase strings for
//! keyword tokens (`package`, `fun`, `class`), UPPER_SNAKE for
//! composite and most token kinds (`PACKAGE_DIRECTIVE`, `IDENTIFIER`,
//! `DOT`), and `kotlin.FILE` for the file root. We mirror that here
//! so YAML diffs against the reference psi.yaml file are stable.

use skotch_syntax::SyntaxKind;

/// Returns the string written into the YAML `type:` field for `kind`.
pub fn syntax_kind_name(kind: SyntaxKind) -> &'static str {
    use SyntaxKind::*;
    match kind {
        // ─── special ───
        TOMBSTONE => "TOMBSTONE",
        EOF => "EOF",
        ERROR_ELEMENT => "ERROR_ELEMENT",
        FILE => "kotlin.FILE",

        // ─── composite — declarations / file structure ───
        PACKAGE_DIRECTIVE => "PACKAGE_DIRECTIVE",
        IMPORT_LIST => "IMPORT_LIST",
        IMPORT_DIRECTIVE => "IMPORT_DIRECTIVE",
        IMPORT_ALIAS => "IMPORT_ALIAS",
        CLASS => "CLASS",
        OBJECT_DECLARATION => "OBJECT_DECLARATION",
        COMPANION_OBJECT => "OBJECT_DECLARATION",
        INTERFACE => "CLASS",
        ENUM_CLASS => "CLASS",
        ENUM_ENTRY => "ENUM_ENTRY",
        TYPEALIAS => "TYPEALIAS",
        FUN => "FUN",
        PROPERTY => "PROPERTY",
        PROPERTY_ACCESSOR => "PROPERTY_ACCESSOR",
        PRIMARY_CONSTRUCTOR => "PRIMARY_CONSTRUCTOR",
        SECONDARY_CONSTRUCTOR => "SECONDARY_CONSTRUCTOR",
        CONSTRUCTOR_DELEGATION_CALL => "CONSTRUCTOR_DELEGATION_CALL",
        CONSTRUCTOR_DELEGATION_REFERENCE => "CONSTRUCTOR_DELEGATION_REFERENCE",
        CLASS_BODY => "CLASS_BODY",
        ANONYMOUS_INITIALIZER => "CLASS_INITIALIZER",

        // ─── composite — modifiers / annotations ───
        MODIFIER_LIST => "MODIFIER_LIST",
        ANNOTATION => "ANNOTATION",
        ANNOTATION_ENTRY => "ANNOTATION_ENTRY",
        ANNOTATION_USE_SITE_TARGET => "ANNOTATION_TARGET",
        FILE_ANNOTATION_LIST => "FILE_ANNOTATION_LIST",

        // ─── composite — parameters / arguments ───
        VALUE_PARAMETER_LIST => "VALUE_PARAMETER_LIST",
        VALUE_PARAMETER => "VALUE_PARAMETER",
        VALUE_ARGUMENT_LIST => "VALUE_ARGUMENT_LIST",
        VALUE_ARGUMENT => "VALUE_ARGUMENT",
        VALUE_ARGUMENT_NAME => "VALUE_ARGUMENT_NAME",
        LAMBDA_ARGUMENT => "LAMBDA_ARGUMENT",

        // ─── composite — types ───
        TYPE_PARAMETER_LIST => "TYPE_PARAMETER_LIST",
        TYPE_PARAMETER => "TYPE_PARAMETER",
        TYPE_ARGUMENT_LIST => "TYPE_ARGUMENT_LIST",
        TYPE_PROJECTION => "TYPE_PROJECTION",
        TYPE_REFERENCE => "TYPE_REFERENCE",
        USER_TYPE => "USER_TYPE",
        NULLABLE_TYPE => "NULLABLE_TYPE",
        FUNCTION_TYPE => "FUNCTION_TYPE",
        FUNCTION_TYPE_RECEIVER => "FUNCTION_TYPE_RECEIVER",
        DYNAMIC_TYPE => "DYNAMIC_TYPE",
        TYPE_CONSTRAINT_LIST => "TYPE_CONSTRAINT_LIST",
        TYPE_CONSTRAINT => "TYPE_CONSTRAINT",

        // ─── composite — supertypes ───
        SUPER_TYPE_LIST => "SUPER_TYPE_LIST",
        SUPER_TYPE_ENTRY => "SUPER_TYPE_ENTRY",
        DELEGATED_SUPER_TYPE_ENTRY => "DELEGATED_SUPER_TYPE_ENTRY",
        SUPER_TYPE_CALL_ENTRY => "SUPER_TYPE_CALL_ENTRY",
        CONSTRUCTOR_CALLEE => "CONSTRUCTOR_CALLEE",

        // ─── composite — statements / control flow ───
        BLOCK => "BLOCK",
        IF => "IF",
        THEN => "THEN",
        ELSE => "ELSE",
        BODY => "BODY",
        WHEN => "WHEN",
        WHEN_ENTRY => "WHEN_ENTRY",
        WHEN_CONDITION_IN_RANGE => "WHEN_CONDITION_IN_RANGE",
        WHEN_CONDITION_IS_PATTERN => "WHEN_CONDITION_IS_PATTERN",
        WHEN_CONDITION_WITH_EXPRESSION => "WHEN_CONDITION_WITH_EXPRESSION",
        CONDITION => "CONDITION",
        FOR => "FOR",
        WHILE => "WHILE",
        DO_WHILE => "DO_WHILE",
        TRY => "TRY",
        CATCH => "CATCH",
        FINALLY => "FINALLY",
        RETURN => "RETURN",
        THROW => "THROW",
        BREAK => "BREAK",
        CONTINUE => "CONTINUE",
        DESTRUCTURING_DECLARATION => "DESTRUCTURING_DECLARATION",
        DESTRUCTURING_DECLARATION_ENTRY => "DESTRUCTURING_DECLARATION_ENTRY",
        LABELED_STATEMENT => "LABELED_STATEMENT",
        LABEL_QUALIFIER => "LABEL_QUALIFIER",
        LABEL => "LABEL",
        LOOP_RANGE => "LOOP_RANGE",

        // ─── composite — expressions ───
        BINARY_EXPRESSION => "BINARY_EXPRESSION",
        BINARY_WITH_TYPE_RHS_EXPRESSION => "BINARY_WITH_TYPE",
        PREFIX_EXPRESSION => "PREFIX_EXPRESSION",
        POSTFIX_EXPRESSION => "POSTFIX_EXPRESSION",
        UNARY_EXPRESSION => "UNARY_EXPRESSION",
        OPERATION_REFERENCE => "OPERATION_REFERENCE",
        DOT_QUALIFIED_EXPRESSION => "DOT_QUALIFIED_EXPRESSION",
        SAFE_ACCESS_EXPRESSION => "SAFE_ACCESS_EXPRESSION",
        REFERENCE_EXPRESSION => "REFERENCE_EXPRESSION",
        THIS_EXPRESSION => "THIS_EXPRESSION",
        SUPER_EXPRESSION => "SUPER_EXPRESSION",
        CALL_EXPRESSION => "CALL_EXPRESSION",
        LAMBDA_EXPRESSION => "LAMBDA_EXPRESSION",
        FUNCTION_LITERAL => "FUNCTION_LITERAL",
        ARRAY_ACCESS_EXPRESSION => "ARRAY_ACCESS_EXPRESSION",
        INDICES => "INDICES",
        CALLABLE_REFERENCE_EXPRESSION => "CALLABLE_REFERENCE_EXPRESSION",
        CLASS_LITERAL_EXPRESSION => "CLASS_LITERAL_EXPRESSION",
        PARENTHESIZED => "PARENTHESIZED",
        COLLECTION_LITERAL_EXPRESSION => "COLLECTION_LITERAL_EXPRESSION",
        ANNOTATED_EXPRESSION => "ANNOTATED_EXPRESSION",
        LABELED_EXPRESSION => "LABELED_EXPRESSION",
        IS_EXPRESSION => "IS_EXPRESSION",
        OBJECT_LITERAL => "OBJECT_LITERAL",

        // ─── composite — string templates ───
        STRING_TEMPLATE => "STRING_TEMPLATE",
        LITERAL_STRING_TEMPLATE_ENTRY => "LITERAL_STRING_TEMPLATE_ENTRY",
        ESCAPE_STRING_TEMPLATE_ENTRY => "ESCAPE_STRING_TEMPLATE_ENTRY",
        SHORT_STRING_TEMPLATE_ENTRY => "SHORT_STRING_TEMPLATE_ENTRY",
        LONG_STRING_TEMPLATE_ENTRY => "LONG_STRING_TEMPLATE_ENTRY",
        BLOCK_STRING_TEMPLATE_ENTRY => "BLOCK_STRING_TEMPLATE_ENTRY",

        // ─── composite — constants ───
        INTEGER_CONSTANT => "INTEGER_CONSTANT",
        FLOAT_CONSTANT => "FLOAT_CONSTANT",
        BOOLEAN_CONSTANT => "BOOLEAN_CONSTANT",
        CHARACTER_CONSTANT => "CHARACTER_CONSTANT",
        NULL_CONSTANT => "NULL",

        // ─── leaf tokens — identifiers / literals ───
        IDENTIFIER => "IDENTIFIER",
        INTEGER_LITERAL => "INTEGER_LITERAL",
        CHARACTER_LITERAL => "CHARACTER_LITERAL",
        LONG_LITERAL => "INTEGER_LITERAL",
        DOUBLE_LITERAL => "FLOAT_LITERAL",
        FLOAT_LITERAL => "FLOAT_LITERAL",
        STRING_LITERAL => "REGULAR_STRING_PART",
        STRING_START => "OPEN_QUOTE",
        STRING_CHUNK => "REGULAR_STRING_PART",
        STRING_IDENT_REF => "SHORT_TEMPLATE_ENTRY_START",
        STRING_EXPR_START => "LONG_TEMPLATE_ENTRY_START",
        STRING_EXPR_END => "LONG_TEMPLATE_ENTRY_END",
        STRING_END => "CLOSING_QUOTE",
        REGULAR_STRING_PART => "REGULAR_STRING_PART",
        OPEN_QUOTE => "OPEN_QUOTE",
        CLOSING_QUOTE => "CLOSING_QUOTE",
        ESCAPE_SEQUENCE => "ESCAPE_SEQUENCE",

        // ─── keyword tokens — emit lowercase IElementType ───
        KW_FUN => "fun",
        KW_VAL => "val",
        KW_VAR => "var",
        KW_IF => "if",
        KW_ELSE => "else",
        KW_RETURN => "return",
        KW_TRUE => "true",
        KW_FALSE => "false",
        KW_NULL => "null",
        KW_WHILE => "while",
        KW_DO => "do",
        KW_WHEN => "when",
        KW_FOR => "for",
        KW_IN => "in",
        KW_BREAK => "break",
        KW_CONTINUE => "continue",
        KW_CLASS => "class",
        KW_OBJECT => "object",
        KW_PACKAGE => "package",
        KW_IMPORT => "import",
        KW_CONST => "const",
        KW_THROW => "throw",
        KW_TRY => "try",
        KW_CATCH => "catch",
        KW_FINALLY => "finally",
        KW_IS => "is",
        KW_AS => "as",
        KW_SUPER => "super",
        KW_INIT => "init",
        KW_DATA => "data",
        KW_ENUM => "enum",
        KW_INTERFACE => "interface",
        KW_SEALED => "sealed",
        KW_OVERRIDE => "override",
        KW_OPEN => "open",
        KW_ABSTRACT => "abstract",
        KW_INFIX => "infix",
        KW_INLINE => "inline",
        KW_PRIVATE => "private",
        KW_PROTECTED => "protected",
        KW_INTERNAL => "internal",
        KW_OPERATOR => "operator",
        KW_VARARG => "vararg",
        KW_CONSTRUCTOR => "constructor",
        KW_LATEINIT => "lateinit",
        KW_SUSPEND => "suspend",
        KW_TAILREC => "tailrec",
        KW_THIS => "this",
        KW_TYPEALIAS => "typealias",
        KW_BY => "by",
        KW_OUT => "out",
        KW_WHERE => "where",
        KW_ANNOTATION => "annotation",
        KW_COMPANION => "companion",
        KW_REIFIED => "reified",
        KW_VALUE => "value",
        KW_CROSSINLINE => "crossinline",
        KW_NOINLINE => "noinline",
        KW_ACTUAL => "actual",
        KW_EXPECT => "expect",
        KW_FIELD => "field",
        KW_GET => "get",
        KW_SET => "set",
        KW_PARAM => "param",
        KW_PROPERTY => "property",
        KW_RECEIVER => "receiver",
        KW_FILE => "file",
        KW_FUN_INTERFACE => "fun",
        KW_PUBLIC => "public",
        KW_INNER => "inner",

        // ─── punctuation tokens — UPPER_SNAKE per kotlinc ───
        LPAR => "LPAR",
        RPAR => "RPAR",
        LBRACE => "LBRACE",
        RBRACE => "RBRACE",
        LBRACKET => "LBRACKET",
        RBRACKET => "RBRACKET",
        COMMA => "COMMA",
        SEMICOLON => "SEMICOLON",
        COLON => "COLON",
        COLONCOLON => "COLONCOLON",
        DOT => "DOT",
        DOTDOT => "RANGE",
        QUEST => "QUEST",
        QUESTDOT => "SAFE_ACCESS",
        AS_SAFE => "AS_SAFE",
        NOT_IS => "NOT_IS",
        NOT_IN => "NOT_IN",
        AT => "AT",
        ARROW => "ARROW",
        EQ => "EQ",
        EQEQ => "EQEQ",
        EXCLEQ => "EXCLEQ",
        EXCL => "EXCL",
        EXCLEXCL => "EXCLEXCL",
        LT => "LT",
        GT => "GT",
        LTEQ => "LTEQ",
        GTEQ => "GTEQ",
        ANDAND => "ANDAND",
        OROR => "OROR",
        PLUS => "PLUS",
        MINUS => "MINUS",
        MUL => "MUL",
        DIV => "DIV",
        PERC => "PERC",
        PLUSEQ => "PLUSEQ",
        MINUSEQ => "MINUSEQ",
        MULEQ => "MULEQ",
        DIVEQ => "DIVEQ",
        PERCEQ => "PERCEQ",
        PLUSPLUS => "PLUSPLUS",
        MINUSMINUS => "MINUSMINUS",
        ELVIS => "ELVIS",
        HASH => "HASH",

        // ─── trivia ───
        WHITE_SPACE => "WHITE_SPACE",
        LINE_COMMENT => "EOL_COMMENT",
        BLOCK_COMMENT => "BLOCK_COMMENT",

        // ─── structural ───
        NEWLINE => "WHITE_SPACE",
        LEX_ERROR => "BAD_CHARACTER",

        // ─── KDoc ───
        KDOC => "KDoc",
        KDOC_START => "KDOC_START",
        KDOC_END => "KDOC_END",
        KDOC_LEADING_ASTERISK => "KDOC_LEADING_ASTERISK",
        KDOC_SECTION => "KDOC_SECTION",
        KDOC_TAG => "KDOC_TAG",
        KDOC_TAG_NAME => "KDOC_TAG_NAME",
        KDOC_NAME => "KDOC_NAME",
        KDOC_TEXT => "KDOC_TEXT",
        KDOC_CODE_BLOCK_TEXT => "KDOC_CODE_BLOCK_TEXT",
        KDOC_LPAR => "KDOC_LPAR",
        KDOC_RPAR => "KDOC_RPAR",
        KDOC_MARKDOWN_LINK => "KDOC_MARKDOWN_LINK",
        KDOC_MARKDOWN_INLINE_LINK => "KDOC_MARKDOWN_INLINE_LINK",
    }
}

/// Inverse: given the kotlinc-style name, return the [`SyntaxKind`].
/// Used when re-parsing YAML back into a tree. Returns
/// [`SyntaxKind::ERROR_ELEMENT`] for unknown names — the YAML parser
/// keeps going so we still see structural problems instead of
/// rejecting the whole file.
pub fn syntax_kind_from_name(name: &str) -> SyntaxKind {
    use SyntaxKind::*;
    match name {
        // special / file
        "kotlin.FILE" => FILE,
        "TOMBSTONE" => TOMBSTONE,
        "EOF" => EOF,
        "ERROR_ELEMENT" => ERROR_ELEMENT,

        // composites
        "PACKAGE_DIRECTIVE" => PACKAGE_DIRECTIVE,
        "IMPORT_LIST" => IMPORT_LIST,
        "IMPORT_DIRECTIVE" => IMPORT_DIRECTIVE,
        "IMPORT_ALIAS" => IMPORT_ALIAS,
        "CLASS" => CLASS,
        "OBJECT_DECLARATION" => OBJECT_DECLARATION,
        "ENUM_ENTRY" => ENUM_ENTRY,
        "TYPEALIAS" => TYPEALIAS,
        "FUN" => FUN,
        "PROPERTY" => PROPERTY,
        "PROPERTY_ACCESSOR" => PROPERTY_ACCESSOR,
        "PRIMARY_CONSTRUCTOR" => PRIMARY_CONSTRUCTOR,
        "SECONDARY_CONSTRUCTOR" => SECONDARY_CONSTRUCTOR,
        "CONSTRUCTOR_DELEGATION_CALL" => CONSTRUCTOR_DELEGATION_CALL,
        "CONSTRUCTOR_DELEGATION_REFERENCE" => CONSTRUCTOR_DELEGATION_REFERENCE,
        "CLASS_BODY" => CLASS_BODY,
        "CLASS_INITIALIZER" => ANONYMOUS_INITIALIZER,
        "MODIFIER_LIST" => MODIFIER_LIST,
        "ANNOTATION" => ANNOTATION,
        "ANNOTATION_ENTRY" => ANNOTATION_ENTRY,
        "ANNOTATION_TARGET" => ANNOTATION_USE_SITE_TARGET,
        "FILE_ANNOTATION_LIST" => FILE_ANNOTATION_LIST,
        "VALUE_PARAMETER_LIST" => VALUE_PARAMETER_LIST,
        "VALUE_PARAMETER" => VALUE_PARAMETER,
        "VALUE_ARGUMENT_LIST" => VALUE_ARGUMENT_LIST,
        "VALUE_ARGUMENT" => VALUE_ARGUMENT,
        "VALUE_ARGUMENT_NAME" => VALUE_ARGUMENT_NAME,
        "LAMBDA_ARGUMENT" => LAMBDA_ARGUMENT,
        "TYPE_PARAMETER_LIST" => TYPE_PARAMETER_LIST,
        "TYPE_PARAMETER" => TYPE_PARAMETER,
        "TYPE_ARGUMENT_LIST" => TYPE_ARGUMENT_LIST,
        "TYPE_PROJECTION" => TYPE_PROJECTION,
        "TYPE_REFERENCE" => TYPE_REFERENCE,
        "USER_TYPE" => USER_TYPE,
        "NULLABLE_TYPE" => NULLABLE_TYPE,
        "FUNCTION_TYPE" => FUNCTION_TYPE,
        "FUNCTION_TYPE_RECEIVER" => FUNCTION_TYPE_RECEIVER,
        "DYNAMIC_TYPE" => DYNAMIC_TYPE,
        "TYPE_CONSTRAINT_LIST" => TYPE_CONSTRAINT_LIST,
        "TYPE_CONSTRAINT" => TYPE_CONSTRAINT,
        "SUPER_TYPE_LIST" => SUPER_TYPE_LIST,
        "SUPER_TYPE_ENTRY" => SUPER_TYPE_ENTRY,
        "DELEGATED_SUPER_TYPE_ENTRY" => DELEGATED_SUPER_TYPE_ENTRY,
        "SUPER_TYPE_CALL_ENTRY" => SUPER_TYPE_CALL_ENTRY,
        "CONSTRUCTOR_CALLEE" => CONSTRUCTOR_CALLEE,
        "BLOCK" => BLOCK,
        "IF" => IF,
        "THEN" => THEN,
        "ELSE" => ELSE,
        "BODY" => BODY,
        "WHEN" => WHEN,
        "WHEN_ENTRY" => WHEN_ENTRY,
        "WHEN_CONDITION_IN_RANGE" => WHEN_CONDITION_IN_RANGE,
        "WHEN_CONDITION_IS_PATTERN" => WHEN_CONDITION_IS_PATTERN,
        "WHEN_CONDITION_WITH_EXPRESSION" => WHEN_CONDITION_WITH_EXPRESSION,
        "CONDITION" => CONDITION,
        "FOR" => FOR,
        "WHILE" => WHILE,
        "DO_WHILE" => DO_WHILE,
        "TRY" => TRY,
        "CATCH" => CATCH,
        "FINALLY" => FINALLY,
        "RETURN" => RETURN,
        "THROW" => THROW,
        "BREAK" => BREAK,
        "CONTINUE" => CONTINUE,
        "DESTRUCTURING_DECLARATION" => DESTRUCTURING_DECLARATION,
        "DESTRUCTURING_DECLARATION_ENTRY" => DESTRUCTURING_DECLARATION_ENTRY,
        "LABELED_STATEMENT" => LABELED_STATEMENT,
        "LABEL_QUALIFIER" => LABEL_QUALIFIER,
        "LABEL" => LABEL,
        "LOOP_RANGE" => LOOP_RANGE,
        "BINARY_EXPRESSION" => BINARY_EXPRESSION,
        "BINARY_WITH_TYPE" => BINARY_WITH_TYPE_RHS_EXPRESSION,
        "PREFIX_EXPRESSION" => PREFIX_EXPRESSION,
        "POSTFIX_EXPRESSION" => POSTFIX_EXPRESSION,
        "UNARY_EXPRESSION" => UNARY_EXPRESSION,
        "OPERATION_REFERENCE" => OPERATION_REFERENCE,
        "DOT_QUALIFIED_EXPRESSION" => DOT_QUALIFIED_EXPRESSION,
        "SAFE_ACCESS_EXPRESSION" => SAFE_ACCESS_EXPRESSION,
        "REFERENCE_EXPRESSION" => REFERENCE_EXPRESSION,
        "THIS_EXPRESSION" => THIS_EXPRESSION,
        "SUPER_EXPRESSION" => SUPER_EXPRESSION,
        "CALL_EXPRESSION" => CALL_EXPRESSION,
        "LAMBDA_EXPRESSION" => LAMBDA_EXPRESSION,
        "FUNCTION_LITERAL" => FUNCTION_LITERAL,
        "ARRAY_ACCESS_EXPRESSION" => ARRAY_ACCESS_EXPRESSION,
        "INDICES" => INDICES,
        "CALLABLE_REFERENCE_EXPRESSION" => CALLABLE_REFERENCE_EXPRESSION,
        "CLASS_LITERAL_EXPRESSION" => CLASS_LITERAL_EXPRESSION,
        "PARENTHESIZED" => PARENTHESIZED,
        "COLLECTION_LITERAL_EXPRESSION" => COLLECTION_LITERAL_EXPRESSION,
        "ANNOTATED_EXPRESSION" => ANNOTATED_EXPRESSION,
        "LABELED_EXPRESSION" => LABELED_EXPRESSION,
        "IS_EXPRESSION" => IS_EXPRESSION,
        "OBJECT_LITERAL" => OBJECT_LITERAL,
        "STRING_TEMPLATE" => STRING_TEMPLATE,
        "LITERAL_STRING_TEMPLATE_ENTRY" => LITERAL_STRING_TEMPLATE_ENTRY,
        "ESCAPE_STRING_TEMPLATE_ENTRY" => ESCAPE_STRING_TEMPLATE_ENTRY,
        "SHORT_STRING_TEMPLATE_ENTRY" => SHORT_STRING_TEMPLATE_ENTRY,
        "LONG_STRING_TEMPLATE_ENTRY" => LONG_STRING_TEMPLATE_ENTRY,
        "BLOCK_STRING_TEMPLATE_ENTRY" => BLOCK_STRING_TEMPLATE_ENTRY,
        "INTEGER_CONSTANT" => INTEGER_CONSTANT,
        "FLOAT_CONSTANT" => FLOAT_CONSTANT,
        "BOOLEAN_CONSTANT" => BOOLEAN_CONSTANT,
        "CHARACTER_CONSTANT" => CHARACTER_CONSTANT,
        "NULL" => NULL_CONSTANT,

        // leaf tokens
        "IDENTIFIER" => IDENTIFIER,
        "INTEGER_LITERAL" => INTEGER_LITERAL,
        "CHARACTER_LITERAL" => CHARACTER_LITERAL,
        "FLOAT_LITERAL" => FLOAT_LITERAL,
        "OPEN_QUOTE" => OPEN_QUOTE,
        "CLOSING_QUOTE" => CLOSING_QUOTE,
        "REGULAR_STRING_PART" => REGULAR_STRING_PART,
        "ESCAPE_SEQUENCE" => ESCAPE_SEQUENCE,
        "SHORT_TEMPLATE_ENTRY_START" => STRING_IDENT_REF,
        "LONG_TEMPLATE_ENTRY_START" => STRING_EXPR_START,
        "LONG_TEMPLATE_ENTRY_END" => STRING_EXPR_END,

        // keywords
        "fun" => KW_FUN,
        "val" => KW_VAL,
        "var" => KW_VAR,
        "if" => KW_IF,
        "else" => KW_ELSE,
        "return" => KW_RETURN,
        "true" => KW_TRUE,
        "false" => KW_FALSE,
        "null" => KW_NULL,
        "while" => KW_WHILE,
        "do" => KW_DO,
        "when" => KW_WHEN,
        "for" => KW_FOR,
        "in" => KW_IN,
        "break" => KW_BREAK,
        "continue" => KW_CONTINUE,
        "class" => KW_CLASS,
        "object" => KW_OBJECT,
        "package" => KW_PACKAGE,
        "import" => KW_IMPORT,
        "const" => KW_CONST,
        "throw" => KW_THROW,
        "try" => KW_TRY,
        "catch" => KW_CATCH,
        "finally" => KW_FINALLY,
        "is" => KW_IS,
        "as" => KW_AS,
        "super" => KW_SUPER,
        "init" => KW_INIT,
        "data" => KW_DATA,
        "enum" => KW_ENUM,
        "interface" => KW_INTERFACE,
        "sealed" => KW_SEALED,
        "override" => KW_OVERRIDE,
        "open" => KW_OPEN,
        "abstract" => KW_ABSTRACT,
        "infix" => KW_INFIX,
        "inline" => KW_INLINE,
        "private" => KW_PRIVATE,
        "protected" => KW_PROTECTED,
        "internal" => KW_INTERNAL,
        "operator" => KW_OPERATOR,
        "vararg" => KW_VARARG,
        "constructor" => KW_CONSTRUCTOR,
        "lateinit" => KW_LATEINIT,
        "suspend" => KW_SUSPEND,
        "tailrec" => KW_TAILREC,
        "this" => KW_THIS,
        "typealias" => KW_TYPEALIAS,
        "by" => KW_BY,
        "out" => KW_OUT,
        "where" => KW_WHERE,
        "annotation" => KW_ANNOTATION,
        "companion" => KW_COMPANION,
        "reified" => KW_REIFIED,
        "value" => KW_VALUE,
        "crossinline" => KW_CROSSINLINE,
        "noinline" => KW_NOINLINE,
        "actual" => KW_ACTUAL,
        "expect" => KW_EXPECT,
        "field" => KW_FIELD,
        "get" => KW_GET,
        "set" => KW_SET,
        "param" => KW_PARAM,
        "property" => KW_PROPERTY,
        "receiver" => KW_RECEIVER,
        "file" => KW_FILE,
        "public" => KW_PUBLIC,
        "inner" => KW_INNER,

        // punctuation
        "LPAR" => LPAR,
        "RPAR" => RPAR,
        "LBRACE" => LBRACE,
        "RBRACE" => RBRACE,
        "LBRACKET" => LBRACKET,
        "RBRACKET" => RBRACKET,
        "COMMA" => COMMA,
        "SEMICOLON" => SEMICOLON,
        "COLON" => COLON,
        "COLONCOLON" => COLONCOLON,
        "DOT" => DOT,
        "RANGE" => DOTDOT,
        "QUEST" => QUEST,
        "SAFE_ACCESS" => QUESTDOT,
        "AS_SAFE" => AS_SAFE,
        "NOT_IS" => NOT_IS,
        "NOT_IN" => NOT_IN,
        "AT" => AT,
        "ARROW" => ARROW,
        "EQ" => EQ,
        "EQEQ" => EQEQ,
        "EXCLEQ" => EXCLEQ,
        "EXCL" => EXCL,
        "EXCLEXCL" => EXCLEXCL,
        "LT" => LT,
        "GT" => GT,
        "LTEQ" => LTEQ,
        "GTEQ" => GTEQ,
        "ANDAND" => ANDAND,
        "OROR" => OROR,
        "PLUS" => PLUS,
        "MINUS" => MINUS,
        "MUL" => MUL,
        "DIV" => DIV,
        "PERC" => PERC,
        "PLUSEQ" => PLUSEQ,
        "MINUSEQ" => MINUSEQ,
        "MULEQ" => MULEQ,
        "DIVEQ" => DIVEQ,
        "PERCEQ" => PERCEQ,
        "PLUSPLUS" => PLUSPLUS,
        "MINUSMINUS" => MINUSMINUS,
        "ELVIS" => ELVIS,
        "HASH" => HASH,

        // trivia
        "WHITE_SPACE" => WHITE_SPACE,
        "EOL_COMMENT" => LINE_COMMENT,
        "BLOCK_COMMENT" => BLOCK_COMMENT,
        "BAD_CHARACTER" => LEX_ERROR,

        // kdoc
        "KDoc" => KDOC,
        "KDOC_START" => KDOC_START,
        "KDOC_END" => KDOC_END,
        "KDOC_LEADING_ASTERISK" => KDOC_LEADING_ASTERISK,
        "KDOC_SECTION" => KDOC_SECTION,
        "KDOC_TAG" => KDOC_TAG,
        "KDOC_TAG_NAME" => KDOC_TAG_NAME,
        "KDOC_NAME" => KDOC_NAME,
        "KDOC_TEXT" => KDOC_TEXT,
        "KDOC_CODE_BLOCK_TEXT" => KDOC_CODE_BLOCK_TEXT,
        "KDOC_LPAR" => KDOC_LPAR,
        "KDOC_RPAR" => KDOC_RPAR,
        "KDOC_MARKDOWN_LINK" => KDOC_MARKDOWN_LINK,
        "KDOC_MARKDOWN_INLINE_LINK" => KDOC_MARKDOWN_INLINE_LINK,

        _ => ERROR_ELEMENT,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use skotch_syntax::SyntaxKind;

    #[test]
    fn file_root_uses_kotlin_dot_prefix() {
        assert_eq!(syntax_kind_name(SyntaxKind::FILE), "kotlin.FILE");
    }

    #[test]
    fn keywords_are_lowercase() {
        assert_eq!(syntax_kind_name(SyntaxKind::KW_PACKAGE), "package");
        assert_eq!(syntax_kind_name(SyntaxKind::KW_FUN), "fun");
        assert_eq!(syntax_kind_name(SyntaxKind::KW_CLASS), "class");
    }

    #[test]
    fn composites_are_upper_snake() {
        assert_eq!(
            syntax_kind_name(SyntaxKind::PACKAGE_DIRECTIVE),
            "PACKAGE_DIRECTIVE"
        );
        assert_eq!(
            syntax_kind_name(SyntaxKind::DOT_QUALIFIED_EXPRESSION),
            "DOT_QUALIFIED_EXPRESSION"
        );
    }

    #[test]
    fn round_trip_through_names() {
        // For non-aliased kinds, name → kind → name is stable.
        for k in [
            SyntaxKind::FILE,
            SyntaxKind::PACKAGE_DIRECTIVE,
            SyntaxKind::FUN,
            SyntaxKind::IDENTIFIER,
            SyntaxKind::KW_PACKAGE,
            SyntaxKind::DOT,
            SyntaxKind::WHITE_SPACE,
            SyntaxKind::KDOC,
        ] {
            let name = syntax_kind_name(k);
            assert_eq!(
                syntax_kind_from_name(name),
                k,
                "round-trip failed for {:?}",
                k
            );
        }
    }
}
