//! 12 SIL byte-identity goldens from real-world Kotlin.
//!
//! Sourced from the parity fixtures (clikt 5.1, kotlincrypto-hash 0.8,
//! ktlint 1.8). Each test asserts:
//!
//! 1. **Byte-identical YAML.** The SIL output for the `.kt` file
//!    matches the companion `.yaml` (generated by the reference
//!    `scripts/kotlin-psi.main.kts`) exactly.
//! 2. **Lossless parse.** Concatenating every leaf's text reproduces
//!    the source byte-for-byte (modulo CRLF normalization).
//! 3. **Idempotent emit.** Re-parsing the YAML and re-emitting it
//!    yields the same YAML bytes.
//! 4. **Performance.** Each file parses + emits YAML in well under
//!    250 ms (debug build); the 12-file aggregate parses in under 5 s.
//!
//! These 12 files exercise: file-level `@file:` annotations, license
//! block comments, KDoc with markdown links and tag continuation,
//! data classes, sealed classes, primary + secondary constructors,
//! companion objects, extension functions, generic type params,
//! `when` expressions, `try/catch/finally`, lambdas, string templates,
//! escape sequences, nested function types, operator overloading, and
//! more — across 1700+ lines of Kotlin total.

use skotch_sil::{emit_yaml, parse_sil, parse_yaml};
use std::time::Instant;

const GOLDENS: &[&str] = &[
    "01_text.kt",
    "02_ParameterGroup.kt",
    "03_TupleHash128.kt",
    "04_PlainSummaryReporter.kt",
    "05_MaxLineLengthEditorConfigProperty.kt",
    "06_AnnotationSpacingRule.kt",
    "07_EnumWrappingRule.kt",
    "08_ModifierOrderRule.kt",
    "09_StatementWrappingRule.kt",
    "10_UnnecessaryParenthesesBeforeTrailingLambdaRule.kt",
    "11_JsonReporterTest.kt",
    "12_KtlintCliTask.kt",
];

fn goldens_dir() -> std::path::PathBuf {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    std::path::PathBuf::from(manifest).join("tests/goldens")
}

/// Normalize CRLF → LF the same way `parse_sil` does internally, so
/// the byte-equality check below isn't fooled by source on disk.
fn normalize(src: &str) -> String {
    if src.contains('\r') {
        src.replace("\r\n", "\n").replace('\r', "\n")
    } else {
        src.to_string()
    }
}

/// First-divergence diff for a useful error message.
fn first_divergence(actual: &str, expected: &str) -> String {
    let a: Vec<&str> = actual.lines().collect();
    let e: Vec<&str> = expected.lines().collect();
    let common = a.len().min(e.len());
    let Some(idx) = (0..common).find(|&i| a[i] != e[i]) else {
        return format!(
            "lengths differ: actual={} lines, expected={} lines",
            a.len(),
            e.len()
        );
    };
    let lo = idx.saturating_sub(3);
    let hi_a = (idx + 10).min(a.len());
    let hi_e = (idx + 10).min(e.len());
    format!(
        "first diff at line {}:\n--- actual ---\n{}\n--- expected ---\n{}\n(actual {} lines, expected {} lines)",
        idx + 1,
        a[lo..hi_a].join("\n"),
        e[lo..hi_e].join("\n"),
        a.len(),
        e.len(),
    )
}

fn check_golden(name: &str) {
    let dir = goldens_dir();
    let kt_path = dir.join(name);
    let yaml_path = dir.join(format!("{}.yaml", &name[..name.len() - 3]));
    let src =
        std::fs::read_to_string(&kt_path).unwrap_or_else(|_| panic!("read {}", kt_path.display()));
    let expected_yaml = std::fs::read_to_string(&yaml_path)
        .unwrap_or_else(|_| panic!("read {}", yaml_path.display()));
    let normalized = normalize(&src);

    // Phase 1: parse, emit YAML.
    let t0 = Instant::now();
    let tree = parse_sil(name, &src);
    let yaml = emit_yaml(&tree);
    let parse_emit_elapsed = t0.elapsed();

    // Performance gate. Debug-build threshold; release runs ~10× faster.
    assert!(
        parse_emit_elapsed.as_millis() < 250,
        "{}: parse + emit took {:?} (> 250 ms)",
        name,
        parse_emit_elapsed,
    );

    // Phase 2: leaf-text concatenation must reproduce the source —
    // checked even if the YAML diverges, so robustness regressions
    // can be diagnosed separately from kotlinc-shape divergences.
    let reconstructed = tree.reconstruct();
    assert_eq!(
        reconstructed, normalized,
        "{}: SIL tree leaves don't reconstruct the source",
        name,
    );

    // Phase 3: byte-identical YAML with the reference.
    if yaml != expected_yaml {
        panic!(
            "{}: SIL YAML differs from reference\n{}",
            name,
            first_divergence(&yaml, &expected_yaml),
        );
    }

    // Phase 4: YAML re-parses + re-emits idempotent.
    let reparsed =
        parse_yaml(&yaml).unwrap_or_else(|e| panic!("{}: re-parse YAML failed: {}", name, e));
    let yaml2 = emit_yaml(&reparsed);
    assert_eq!(
        yaml, yaml2,
        "{}: YAML emit is not idempotent under re-parse",
        name,
    );

    use skotch_syntax::SyntaxKind;
    assert_eq!(
        tree.root.kind,
        SyntaxKind::FILE,
        "{}: root should be FILE",
        name
    );
}

macro_rules! golden_test {
    ($name:ident, $file:expr) => {
        #[test]
        fn $name() {
            check_golden($file);
        }
    };
}

golden_test!(g01_text, "01_text.kt");
golden_test!(g02_parameter_group, "02_ParameterGroup.kt");
golden_test!(g03_tuple_hash_128, "03_TupleHash128.kt");
golden_test!(g04_plain_summary_reporter, "04_PlainSummaryReporter.kt");
golden_test!(
    g05_max_line_length_editor_config_property,
    "05_MaxLineLengthEditorConfigProperty.kt"
);
golden_test!(g06_annotation_spacing_rule, "06_AnnotationSpacingRule.kt");
golden_test!(g07_enum_wrapping_rule, "07_EnumWrappingRule.kt");
golden_test!(g08_modifier_order_rule, "08_ModifierOrderRule.kt");
golden_test!(g09_statement_wrapping_rule, "09_StatementWrappingRule.kt");
golden_test!(
    g10_unnecessary_parens_before_trailing_lambda,
    "10_UnnecessaryParenthesesBeforeTrailingLambdaRule.kt"
);
golden_test!(g11_json_reporter_test, "11_JsonReporterTest.kt");
golden_test!(g12_ktlint_cli_task, "12_KtlintCliTask.kt");

/// Aggregate performance smoke test: parsing all 12 goldens (1700+
/// LOC, ~2 MB of reference YAML output) must complete in under 5 s
/// in debug mode.
#[test]
fn all_goldens_parse_quickly() {
    let dir = goldens_dir();
    let t0 = Instant::now();
    let mut total_src = 0usize;
    let mut total_yaml = 0usize;
    for name in GOLDENS {
        let src = std::fs::read_to_string(dir.join(name)).expect("read kt");
        total_src += src.len();
        let tree = parse_sil(*name, &src);
        let yaml = emit_yaml(&tree);
        total_yaml += yaml.len();
    }
    let elapsed = t0.elapsed();
    eprintln!(
        "Parsed {} bytes of Kotlin into {} bytes of YAML across {} files in {:?}",
        total_src,
        total_yaml,
        GOLDENS.len(),
        elapsed,
    );
    assert!(
        elapsed.as_secs() < 5,
        "12 goldens took {:?} (> 5 s threshold) — perf regression?",
        elapsed,
    );
}
